name: Docker CICD workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v2 

        - name: Build docker file
          run: |
            docker build -t eks-2048 .

        - name: Push docker image to ECR
          run: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
            docker build -t 2048-app .
            docker tag 2048-app:latest ${{ secrets.ECR_REGISTRY }}/2048-app:latest
            docker push ${{ secrets.ECR_REGISTRY }}/2048-app:latest



             
           
